name: Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn export

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::362322477507:role/s3-upload
          aws-region: us-east-1

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync ./out s3://manly-static-nextjs
